#!/bin/bash 

rm -rf public
hugo
rm -rf gitlab
git clone git@gitlab.com:zzh8829/zihao-pages.git gitlab
rm -rf gitlab/*
cp -r gitlab-pages/. gitlab/
mv public gitlab/
cd gitlab
git add .
git commit -m "Update pages $(date)"
git push origin master
